### ISSUE TITLE
Setting up Kanban board

### ISSUE THREAD

**Issue by CollinsTatang** [CollinsTatang/react-group-project#25]
[react-group-project](https://github.com/CollinsTatang/react-group-project.git)
This project is to be carryout by two partners @CollinsTatang and @denisdiaconu.

**Comment by hemantso** [comment]
Hi @CollinsTatang and @denisdiaconu , 

## Your project is complete!
 There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
